name: hinokifix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase (только авторизация)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_svg: ^2.2.3
  carousel_slider: ^5.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NuromMedium  # Название шрифта
      fonts:
        - asset: assets/Nurom Medium.ttf
  assets:
    - assets/icons/
